### PR TITLE
Handle Error objects with circular references

### PR DESCRIPTION
**Pull request by dkrantsberg**
### Description
Handle Error objetcs containing circular references. 

#### Related issues
- connect to #84

### Checklist
- [x] New tests added or existing tests modified to cover all changes

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
Thank you @dkrantsberg for the pull request. The changes look good at high-level, there is only one thing I'd like to discuss: the choice of the module providing `JSON.stringify` functionality.

Personally, I would pick [fast-safe-stringify](https://www.npmjs.com/package/fast-safe-stringify) -  it can deal with circular references and also provides excellent performance.

What are your arguments for choosing [safe-json-stringify](https://www.npmjs.com/package/safe-json-stringify)?

||npm downloads (weekly)|GitHub stars|Contributors|Used by (repos)|Used by (packages)|
|-|-:|-:|-:|-:|-:|
|fast-safe-stringify|1,625,259|166|11|55,232|299|
|safe-json-stringify|754,580|31|6|84,503|104|

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by dkrantsberg** [comment]
@bajtos , I have no arguments in favor of `safe-json-stringify`. It was just the first library I came across. Let me replace it with `fast-json-stringify`...

**Comment by bajtos** [comment]
Landed 🎉  Thank you @dkrantsberg for the contribution! ❤️

**Pull request merged**
