### PR TITLE
Bump js2xmlparser dependency to version 3.0.0

### PR DESCRIPTION
**Pull request by mattyod**
### Description

Having some issues caused by js2xmlparsers dependency on xmlcreate at version 0.1.1 so updated.

#### Related issues

- None

### Checklist

- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
Hi, thank you @mattyod for the pull request.

> Having some issues caused by js2xmlparsers dependency on xmlcreate at version 0.1.1 so updated.

Could you please be more specific? Ideally, I would like to see a test that fails on the current `master` and passes with your fix in place.

**Comment by bajtos** [comment]
@slnode test please

**Comment by mattyod** [comment]
Sorry this wasn't actually a code error but an npm issue with our build and deploy scripts. Difficult for me to share logs but 0.1.1 version wouldn't install for our build. bluemix/shrinkwrap/nsp etcetera

**Comment by bajtos** [comment]
Fair enough. AFAICT from [the diff](https://github.com/michaelkourlas/node-js2xmlparser/compare/v2.0.2...v3.0.0), the are no significant breaking changes between 2.0.2 and 3.0.0 that would affect strong-error-handler. Let's get this patch landed then!

**Comment by bajtos** [comment]
Thank you for your contribution, @mattyod 🎉

**Comment by mattyod** [comment]
Thank you, quick release to npm much appreciated 👍

**Comment by gsaini** [comment]
Thank you guys for quick release. 👍

**Pull request merged**
