### PR TITLE
update a readme

### PR DESCRIPTION
**Pull request by zhe1ka**
".ok\W+to\W+test."

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by zhe1ka** [comment]
".ok\W+to\W+test."

**Comment by bajtos** [comment]
Hi @zhe1ka, thank you for taking the time to submit a patch improving our documentation!

I need you to sign our Contributors License Agreement before I can land your changes, see the red failed check at the bottom of this page. Here is a direct link for your convenience: https://cla.strongloop.com/agreements/strongloop/strong-error-handler

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
Could you also improve the commit message to make it more descriptive? See our [Git Commit Messsage Guidelines](http://loopback.io/doc/en/contrib/git-commit-messages.html).

I am proposing `README: add missing quotes in a JSON example`

If you are not familiar with git history manipulation, here are the two commands to use: `git commit --amend` and then `git push -f`.

**Comment by bajtos** [comment]
I am closing this pull request as abandoned. @zhe1ka feel free to reopen if/when you get time to address the comments above.

**Pull request closed without merging**
