### PR TITLE
add xml error output support

### PR DESCRIPTION
**Pull request by aozisik**
### Description

This adds xml support

#### Related issues

- strongloop/strong-error-handler#4

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by davidcheung** [comment]
@aozisik thanks for your contribution!
can you also add tests similar to the other 2 formats, to prove that the solution works as intended, as well as prevent from regression later.

**Comment by aozisik** [comment]
I have added tests and squashed commits into a single one.

**Comment by davidcheung** [comment]
@aozisik Thanks for your contribution! landed.

will update the original task to just update docs to reflect supported types

**Comment by bajtos** [comment]
Nice, thank you @aozisik for this contribution! 👏

**Pull request merged**
