### PR TITLE
typo ?

### PR DESCRIPTION
**Pull request by brownman**
rm ','

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by davidcheung** [comment]
thanks @brownman, can you sign the CLA as well?
and can u change the commit title to something like 
>fix typo in readme


@slnode test please

**Comment by superkhau** [comment]
Closing as rejected as the trailing comma should be there.

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by superkhau** [comment]
Looked at this more carefully after being ping by @davidcheung, this is legit. Reopening.

**Comment by superkhau** [comment]
@brownman Can you sign he CLA please? :bowing_man:

**Comment by davidcheung** [comment]
@brownman thanks for the contribution, closing this in favor of #36

**Pull request closed without merging**
