### PR TITLE
Safe fields property description

### PR DESCRIPTION
**Pull request by zbarbuto**
### Description
Adds description of safe fields property to README.md as requested in #7 

cc @bajtos 

#### Related issues

- #7

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
Landed, thank you!

**Pull request merged**
