### PR TITLE
Fixed order of arguments in comment of negotiateContentProducer.

### PR DESCRIPTION
**Pull request by charlie-s**
### Description

Fixed order of arguments in comment of negotiateContentProducer.

#### Related issues

- #46 

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by charlie-s** [comment]
My bad on the commit message linting issue. Does that need to be adjusted?

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
Landed 🎉  thank you for the contribution! 👍

**Pull request merged**
